### ISSUE TITLE
GLFW error 65543

### ISSUE THREAD

**Issue by VedikaSrivastava** [minerllabs/basalt-2022-behavioural-cloning-baseline#8]
![image](https://user-images.githubusercontent.com/83489280/195257673-68d59c8d-d88c-4d2e-87b3-e0c68447c85e.png)

can someone pls help me with this, i have already updated all the drivers yet i keep receiving this same error.

**Comment by Miffyli** [comment]
Hey, I assumed this was resolved in #7 ? You need to remember to add the `xvfb-run` at the beginning of the command every time you run your MineRL code. I do not know if will through X-forwarding (this is what it is trying to do)

**Comment by VedikaSrivastava** [comment]
> Hey, I assumed this was resolved in #7 ? You need to remember to add the `xvfb-run` at the beginning of the command every time you run your MineRL code. I do not know if will through X-forwarding (this is what it is trying to do)

i tried, with `xvfb-run -a` too. It just keeps running and there is no gui or anything

**Comment by Miffyli** [comment]
Yes, that is expected behaviour. With xvfb-run, you will not be able to see the window on the screen as it is being rendered into a virtual buffer (which bypasses the errors you were getting). You could record the videos of the gameplay with cv2 for later viewing.

**Comment by VedikaSrivastava** [comment]
> Yes, that is expected behaviour. With xvfb-run, you will not be able to see the window on the screen as it is being rendered into a virtual buffer (which bypasses the errors you were getting). You could record the videos of the gameplay with cv2 for later viewing.

okay, thank you!

can you also share with me the steps/command to "record the videos of the gameplay with cv2 for later viewing"?

**Comment by Miffyli** [comment]
See e.g., this example how to use the `VideoWriter` class in cv2: https://stackoverflow.com/a/29317298

**Comment by VedikaSrivastava** [comment]
> See e.g., this example how to use the `VideoWriter` class in cv2: https://stackoverflow.com/a/29317298

Thank you!
